In [8]:
import pandas as pd

data = {'age': ['<=30', '<=30', '31...40', '>40', '>40', '>40', '31...40', '<=30', '<=30', '>40', '<=30', '31...40', '31...40', '>40'],
        'income': ['high', 'high', 'high', 'medium', 'low', 'low', 'low', 'medium', 'low', 'medium', 'medium', 'medium', 'high', 'medium'],
        'student': ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no'],
        'credit_rating': ['fair', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'excellent'],
        'computer': ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']}

df = pd.DataFrame(data)

(df)

        age  income student credit_rating computer
0      <=30    high      no          fair       no
1      <=30    high      no     excellent       no
2   31...40    high      no          fair      yes
3       >40  medium      no          fair      yes
4       >40     low     yes          fair      yes
5       >40     low     yes     excellent       no
6   31...40     low     yes     excellent      yes
7      <=30  medium      no          fair       no
8      <=30     low     yes          fair      yes
9       >40  medium     yes          fair      yes
10     <=30  medium     yes     excellent      yes
11  31...40  medium      no     excellent      yes
12  31...40    high     yes          fair      yes
13      >40  medium      no     excellent       no

In [9]:
import pandas as pd

data = {'age': ['<=30', '<=30', '31...40', '>40', '>40', '>40', '31...40', '<=30', '<=30', '>40', '<=30', '31...40', '31...40', '>40'],
        'income': ['high', 'high', 'high', 'medium', 'low', 'low', 'low', 'medium', 'low', 'medium', 'medium', 'medium', 'high', 'medium'],
        'student': ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no'],
        'credit_rating': ['fair', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'excellent'],
        'computer': ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']}

df = pd.DataFrame(data)

P_buys_computer_yes = 9/14
P_buys_computer_no = 5/14

P_age_young_given_yes = 2/9
P_age_young_given_no = 3/5

P_income_medium_given_yes = 4/9
P_income_medium_given_no = 2/5

P_student_yes_given_yes = 6/9
P_student_yes_given_no = 1/5

P_credit_rating_fair_given_yes = 6/9
P_credit_rating_fair_given_no = 2/5

# ornek X icin
age = 'young'
income = 'medium'
student = 'yes'
credit_rating = 'fair'

# hesapla P(X|buys_computer = "yes")
P_X_given_yes = P_age_young_given_yes * P_income_medium_given_yes * P_student_yes_given_yes * P_credit_rating_fair_given_yes

# hesapla P(X|buys_computer = "no")
P_X_given_no = P_age_young_given_no * P_income_medium_given_no * P_student_yes_given_no * P_credit_rating_fair_given_no

# hesapla P(X) = P(X|buys_computer = "yes") * P(buys_computer = "yes") + P(X|buys_computer = "no") * P(buys_computer = "no")
P_X = P_X_given_yes * P_buys_computer_yes + P_X_given_no * P_buys_computer_no

# hesapla P(X|buys_computer = "yes") * P(buys_computer = "yes")
P_X_buys_computer_yes = P_X_given_yes * P_buys_computer_yes

# hesapla P(X|buys_computer = "no") * P(buys_computer = "no")
P_X_buys_computer_no = P_X_given_no * P_buys_computer_no


if P_X_buys_computer_yes > P_X_buys_computer_no:
    result = "buys_computer = yes"
else:
    result = "buys_computer = no"


print("P(X|buys_computer = yes):", P_X_given_yes)
print("P(X|buys_computer = no):", P_X_given_no)
print("P(X):", P_X)
print("P(X buys_computer = yes) P(buys_computer = yes):", P_X_buys_computer_yes)
print("P(X|buys_computer = no) P(buys_computer = no):", P_X_buys_computer_no)
print("Example X belongs to", result, "class.")

P(X|buys_computer = yes): 0.04389574759945129
P(X|buys_computer = no): 0.019200000000000002
P(X): 0.035075837742504404
P(X buys_computer = yes) P(buys_computer = yes): 0.028218694885361547
P(X|buys_computer = no) P(buys_computer = no): 0.006857142857142858
Example X belongs to buys_computer = yes class.